# Generated by Django 3.2.2 on 2021-05-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
