version: '3.7'

services:
    web:
        image: "${WEB_IMAGE}"
        build: ./app
        command: python manage.py test
        volumes:
        - ./app/:/usr/src/app/
        ports:
        - 8000:8000
        environment:
            - DEBUG=1
            - SECRET_KEY='4cw-%zlf-x)g@95n5v&fjkeslt--evj3s*!q+!6atil_-rf$c='
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - SQL_ENGINE=django.db.backends.postgresql
            - SQL_DATABASE=posdb
            - SQL_USER=root
            - SQL_PASSWORD=password
            - SQL_HOST=db
            - SQL_PORT=5432
            - DATABASE=postgres
        depends_on:
            - db
    db:
        image: postgres:12.2-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=posdb

volumes:
    postgres_data: